### PR TITLE
merging

### PR DESCRIPTION
**Pull request by simplyadrian**

### CODE REVIEW

**Comment by spscacyost** [comment]
ive been thinking about a way to do this slightly differently -- making this role also a playbook of itself directly

**Comment by simplyadrian** [comment]
@spscacyost odd. I wonder what I did wrong..

**Comment by danrue** [comment]
Can I merge this PR? @spscacyost @simplyadrian

**Comment by spscacyost** [comment]
the only thing that id really like to add would be to make it backward compatible wrt supervisor_program=>supervisor_programs ( default supervisor_program to first entry in supervisor_programs )

**Comment by spscacyost** [comment]
https://github.com/spscacyost/ansible-role-supervisor/commit/5d2d6edec06899d7c52ef1e98cb91eaa581d0595
@simplyadrian @danrue

**Comment by simplyadrian** [comment]
Can you set a null value as a default for supervisor_programs. As we discussed in the past we don't want to have to set a value if none is desired... i.e. it may be nice to have supervisor installed but I may not need it to manage anything right away.

**Comment by spscacyost** [comment]
empty list would accomplish (current ) what you desire AFAIK ( installed but no programs ) and seems preferable to ansible null handling ( IMO )

**Comment by simplyadrian** [comment]
please merge this !!!

**Comment by danrue** [comment]
Superseded by #11

**Pull request closed without merging**
